name: Sync to Hugging Face hub
on:
  push:
    branches: [telegram_bot]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
          
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # 1. Force the robot to recognize the 'telegram_bot' branch
          git checkout telegram_bot
          
          # 2. Map the local 'telegram_bot' to the remote 'main'
          # We use the full reference path to stop the 'refspec' error
          git push --force https://Frey500:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/Frey500/SELLICA telegram_bot:main